version: '3.1'
services:
  db:
    image: postgres
    restart: always 
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mydatabase
    ports:
      - 5433:5432
    volumes:
      - ./Database/postgres-data:/var/lib/postgresql/data
      - ./Database/scripts/tables_definition.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./Database/scripts/previous_inserts.sql:/docker-entrypoint-initdb.d/2-schema.sql
    networks: [ 'netdbpostgres' ]

  back:
    build: ./Backend
    ports:
      - "8000:8000"
    volumes:
      - ./Backend:/app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5430/mydatabase
    depends_on:
      - db
    networks:
      - netdbpostgres

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "81:80"
    depends_on:
      - back
    networks:
      - netdbpostgres

networks:
  netdbpostgres: {}
volumes:
  postgres-data:
